"""
Insight provider interface and rule-based implementation.
Implements summarize(), explain(), recommend(), and chat() without external API calls.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

class InsightProvider(ABC):
    """Abstract base class for modular AI layers."""

    @abstractmethod
    async def summarize(self, analysis_results: dict[str, Any]) -> str:
        """Generate an executive text summary of the analysis results."""
        pass

    @abstractmethod
    async def explain(self, insight: dict[str, Any]) -> str:
        """Generate a detailed natural language explanation of an insight."""
        pass

    @abstractmethod
    async def recommend(self, insights: list[dict[str, Any]]) -> list[str]:
        """Recommend business actions based on discovered insights."""
        pass

    @abstractmethod
    async def chat(self, message: str, context: dict[str, Any]) -> str:
        """Answer user questions about the dataset/analysis."""
        pass


class RuleBasedInsightProvider(InsightProvider):
    """Deterministic rule-based implementation of InsightProvider."""

    async def summarize(self, analysis_results: dict[str, Any]) -> str:
        kpis = analysis_results.get("kpis", [])
        insights = analysis_results.get("insights", [])
        anomalies = analysis_results.get("anomalies", [])
        
        kpi_summary = ""
        for k in kpis[:3]:
            kpi_summary += f"• **{k.get('name')}**: {k.get('formatted_value')}\n"

        insight_summary = ""
        for i in insights[:3]:
            insight_summary += f"• {i.get('description')}\n"

        anomaly_text = f"We detected {len(anomalies)} anomalies across the dataset." if anomalies else "No major anomalies were detected."

        summary = (
            f"### Executive Summary\n\n"
            f"Here is an overview of the analysis generated by DetectiveAI.\n\n"
            f"#### Key Metrics\n{kpi_summary if kpi_summary else 'No primary KPIs detected.'}\n"
            f"#### Primary Insights\n{insight_summary if insight_summary else 'No major statistical patterns detected yet.'}\n"
            f"#### Data Quality & Anomalies\n{anomaly_text}\n\n"
            f"Based on the analysis, we recommend reviewing the detailed charts, outlier lists, and running forecasts on temporal metrics."
        )
        return summary

    async def explain(self, insight: dict[str, Any]) -> str:
        cat = insight.get("category", "")
        desc = insight.get("description", "")
        conf = insight.get("confidence_score", 90.0)
        data = insight.get("supporting_data") or {}

        explanation = (
            f"**Insight type**: {cat}\n"
            f"**Confidence**: {conf}%\n\n"
            f"{desc}\n\n"
        )

        if cat == "Concentration":
            pct = data.get("concentration_percentage", "")
            entity = data.get("entity", "").replace("_", " ").title()
            val_col = data.get("value_column", "").replace("_", " ")
            explanation += (
                f"**Detailed Breakdown**:\n"
                f"This follows the classic Pareto principle. A small fraction of your {entity}s "
                f"drive a disproportionate share of total {val_col} ({pct}%). "
                f"This suggests you should focus engagement strategies on these top accounts to maximize retention."
            )
        elif cat == "Correlation":
            corr = data.get("correlation", 0.0)
            col_x = data.get("column_x", "")
            col_y = data.get("column_y", "")
            direction = "positive" if corr > 0 else "negative"
            explanation += (
                f"**Detailed Breakdown**:\n"
                f"The statistical correlation coefficient between '{col_x}' and '{col_y}' is {corr:.2f}. "
                f"This {direction} relationship indicates that as '{col_x}' goes up, '{col_y}' tends to "
                f"{'increase' if corr > 0 else 'decrease'}. This is statistically significant and represents a "
                f"potential leverage point for business intervention."
            )
        elif cat == "Contribution":
            category = data.get("category", "")
            pct = data.get("percentage", 0.0)
            explanation += (
                f"**Detailed Breakdown**:\n"
                f"The value is heavily weighted towards '{category}'. "
                f"This category represents {pct}% of the total volume. "
                f"While this represents a strong niche, it also exposes the business to concentration risk "
                f"if market dynamics for '{category}' change."
            )
        elif cat == "Temporal Pattern":
            ratio = data.get("ratio", 1.0)
            diff = data.get("diff_percentage", 0.0)
            explanation += (
                f"**Detailed Breakdown**:\n"
                f"Sales or activity patterns change significantly on the weekends. "
                f"We observed a {diff}% {'increase' if ratio > 1 else 'decrease'} in average volume compared "
                f"to weekdays. Consider tailoring promotional schedules or operational capacity around this weekend cycle."
            )
        else:
            explanation += (
                "**Detailed Breakdown**:\n"
                "This insight was identified via structural pattern analysis. We recommend plotting "
                "the variables over time or by segment to visualize the distributions."
            )

        return explanation

    async def recommend(self, insights: list[dict[str, Any]]) -> list[str]:
        recommendations = []
        categories = {i.get("category") for i in insights}

        if "Concentration" in categories:
            recommendations.append(
                "Establish a VIP customer/product tier program. Focus customer service and high-touch support "
                "on the top 10% cohort that drives the majority of value."
            )
        if "Correlation" in categories:
            recommendations.append(
                "Review pricing and promotion elasticity. If high discounts correlate negatively with revenue/profit, "
                "consider reducing broad markdown rates and moving to targeted loyalty coupons."
            )
        if "Temporal Pattern" in categories:
            recommendations.append(
                "Optimize operational scheduling and staff allocation to align with weekly peak volumes. "
                "Target marketing campaigns on lower-performing days to smooth out demand."
            )
        if "Margin Warning" in categories:
            recommendations.append(
                "Margin warnings detected: Initiate a cost audit for low-margin high-revenue items. Explore suppliers renegotiation, "
                "price increases, or cross-selling higher-margin companion products."
            )
        if "Distribution Imbalance" in categories:
            imbalances = [i for i in insights if i.get("category") == "Distribution Imbalance"]
            for imb in imbalances[:2]:
                data = imb.get("supporting_data") or {}
                col = str(data.get("column", "")).replace("_", " ").title()
                val = str(data.get("value", ""))
                pct = data.get("percentage", 0.0)
                recommendations.append(
                    f"Address distribution skew in '{col}': Since category '{val}' represents a dominant {pct}% "
                    f"concentration of data, evaluate if data collection categories should be collapsed or separate rules applied."
                )
        if "Categorical Association" in categories:
            associations = [i for i in insights if i.get("category") == "Categorical Association"]
            for assoc in associations[:2]:
                data = assoc.get("supporting_data") or {}
                col_a = str(data.get("column_a", "")).replace("_", " ").title()
                val_a = str(data.get("value_a", ""))
                col_b = str(data.get("column_b", "")).replace("_", " ").title()
                val_b = str(data.get("value_b", ""))
                pct = data.get("association_percentage", 0.0)
                recommendations.append(
                    f"Capitalize on rule correlation ({col_a} → {col_b}): Since {pct}% of entries where "
                    f"'{col_a}' is '{val_a}' also show '{col_b}' as '{val_b}', configure business validation rules "
                    f"or operational checklists around this high-probability link."
                )

        # Default recommendations if list is short
        if len(recommendations) < 3:
            recommendations.append(
                "Perform dynamic segmentation checks: Filter the dataset by top categorical fields to inspect "
                "secondary variations in transaction rates and volumes."
            )
            recommendations.append(
                "Run outlier analysis regularly to detect and clean data entry errors or transaction anomalies."
            )
            recommendations.append(
                "Utilize the forecast engine on key numeric variables to budget operational capacity for the next 90 days."
            )

        return recommendations[:5]

    async def chat(self, message: str, context: dict[str, Any]) -> str:
        msg = message.lower().strip()
        
        # Pull details from context
        kpis = context.get("kpis", [])
        insights = context.get("insights", [])
        anomalies = context.get("anomalies", [])
        cleaning_suggestions = context.get("cleaning_suggestions", [])
        forecast = context.get("forecast", {})
        row_count = context.get("row_count") or 0
        col_count = context.get("column_count") or 0
        health_score = context.get("health_score") or 0.0
        profile_data = context.get("profile_data") or {}
        columns_profiles = profile_data.get("columns", [])

        # Helpers
        def format_number(val: Any) -> str:
            if val is None:
                return "N/A"
            if isinstance(val, (int, float)):
                return f"{val:,.2f}" if isinstance(val, float) else f"{val:,}"
            return str(val)

        # 1. Hello / Greetings
        if any(greet in msg for greet in ["hello", "hi", "hey", "greetings", "yo"]):
            return (
                "Hello! I am **DetectiveAI**, your autonomous data analyst assistant. "
                "I have completed a profiling review of this case file. "
                "Ask me anything about its column metrics, null values, outliers, health score, or trends! "
                "For example: *'What is the average of [column_name]?'*, *'Are there missing values?'*, "
                "or *'Show me recommendations.'*"
            )

        # 2. Specific Column Queries
        # Check if the user is asking about a specific column in the dataset
        for col_profile in columns_profiles:
            col_name = col_profile.get("name", "")
            if col_name.lower() in msg:
                classification = col_profile.get("classification", "categorical")
                null_count = col_profile.get("null_count", 0)
                null_pct = col_profile.get("null_percentage", 0.0)
                unique_count = col_profile.get("unique_count", 0)
                
                # Build detail block
                header = f"### Column Profile: `{col_name}`\n"
                type_str = f"• **Data Type**: `{col_profile.get('dtype', 'unknown')}` ({classification})\n"
                completeness = f"• **Missing Values**: {null_count:,} records ({null_pct}% missing)\n"
                uniqueness = f"• **Cardinality**: {unique_count:,} unique values\n"
                
                details = ""
                if classification == "numeric":
                    mean_val = col_profile.get("mean")
                    med_val = col_profile.get("median")
                    min_val = col_profile.get("min")
                    max_val = col_profile.get("max")
                    std_val = col_profile.get("std")
                    mode_val = col_profile.get("mode")
                    
                    details = (
                        f"• **Mean (Average)**: {format_number(mean_val)}\n"
                        f"• **Median**: {format_number(med_val)}\n"
                        f"• **Mode (Most Common)**: {format_number(mode_val)}\n"
                        f"• **Standard Deviation**: {format_number(std_val)}\n"
                        f"• **Range**: {format_number(min_val)} to {format_number(max_val)}\n"
                    )
                else:
                    mode_val = col_profile.get("mode")
                    top_vals = col_profile.get("top_values") or []
                    top_vals_str = ""
                    if top_vals:
                        top_vals_str = "\n".join([f"  - `{v.get('value')}`: {v.get('count'):,} times" for v in top_vals[:5]])
                        top_vals_str = f"\n• **Top Frequent Values**:\n{top_vals_str}"
                    
                    details = (
                        f"• **Mode (Most Common)**: `{mode_val}`\n"
                        f"{top_vals_str}\n"
                    )
                
                return f"{header}{type_str}{completeness}{uniqueness}{details}"

        # 3. Missing values / null values / data quality
        if any(term in msg for term in ["missing", "null", "empty", "blank", "nan", "data quality"]):
            null_cols = []
            for col_profile in columns_profiles:
                nulls = col_profile.get("null_count", 0)
                if nulls > 0:
                    null_cols.append(f"• `{col_profile.get('name')}`: {nulls:,} missing values ({col_profile.get('null_percentage')}% missing)")
            
            if not null_cols:
                return (
                    f"Excellent news! I scanned all **{col_count}** columns and **{row_count:,}** rows, "
                    "and found **zero** missing or null values. The dataset is fully complete!"
                )
            
            null_str = "\n".join(null_cols[:8])
            suggestion_count = len(cleaning_suggestions)
            clean_hint = f"\n\nI identified **{suggestion_count}** quality flags. You can automatically fix these in the **Automatic Cleaning** tab!" if suggestion_count > 0 else ""
            return (
                f"I found missing values in the following columns:\n\n{null_str}"
                f"{clean_hint}"
            )

        # 4. Dataset Health / Quality Index
        if any(term in msg for term in ["health", "score", "integrity", "quality score"]):
            explanation = ""
            if health_score >= 90:
                explanation = "This represents an excellent quality rating. The columns are highly consistent, complete, and have low duplicate levels."
            elif health_score >= 70:
                explanation = "This represents a fair quality rating. There are some missing variables or duplicate transactions, but the overall structure is strong."
            else:
                explanation = "This represents a low quality rating. I recommend applying standard cleaning rules (such as deduplication or filling missing fields) to improve analytical accuracy."

            dupes = profile_data.get("duplicate_row_count", 0)
            dupe_text = f"\n• **Duplicate Rows**: {dupes:,} exact matches" if dupes > 0 else "\n• **Duplicate Rows**: Zero exact duplicates found."
            
            return (
                f"The overall **Dataset Health Score** is **{health_score}%**.\n\n"
                f"{explanation}\n"
                f"• **Total Records**: {row_count:,} rows\n"
                f"• **Total Attributes**: {col_count} columns"
                f"{dupe_text}"
            )

        # 5. Structure / Shape / Rows / Columns
        if any(term in msg for term in ["structure", "columns", "features", "attributes", "fields", "size", "shape", "how many rows"]):
            col_list = [f"`{c.get('name')}`" for c in columns_profiles]
            col_list_str = ", ".join(col_list[:15])
            if len(col_list) > 15:
                col_list_str += f" and {len(col_list) - 15} more..."
                
            types_summary = profile_data.get("data_types_summary", {})
            types_desc = ", ".join([f"{count} {t}" for t, count in types_summary.items()])

            return (
                f"This dataset contains **{row_count:,}** rows and **{col_count}** columns.\n\n"
                f"**Data Types Summary**: {types_desc if types_desc else 'N/A'}\n"
                f"**Columns list**: {col_list_str}"
            )

        # 6. Cleaning suggestions / quality flags
        if any(term in msg for term in ["cleaning", "cleaning suggestion", "imputation", "suggested fix", "how to clean"]):
            if not cleaning_suggestions:
                return (
                    "I analyzed your dataset and found no major quality issues (no duplicates, extreme outliers, or missing values). "
                    "No cleaning actions are recommended at this time!"
                )
            
            clean_list = []
            for idx, sug in enumerate(cleaning_suggestions[:6]):
                col_info = f" in `{sug.get('column')}`" if sug.get("column") else ""
                clean_list.append(f"{idx+1}. **{sug.get('issue_type').replace('_', ' ').title()}**{col_info}: {sug.get('description')} (Suggested fix: *{sug.get('suggested_fix')}*)")
            
            clean_str = "\n".join(clean_list)
            return (
                f"I identified **{len(cleaning_suggestions)}** cleaning suggestions for your dataset:\n\n{clean_str}\n\n"
                "You can review and apply these fixes individually with one click in the **Automatic Cleaning** tab!"
            )

        # 7. Forecast Queries
        if any(term in msg for term in ["forecast", "predict", "future", "arima", "time series"]):
            target_metric = forecast.get("target_column")
            if not target_metric:
                return (
                    "No time-series forecast has been computed yet, or the dataset does not have a temporal column. "
                    "Navigate to the **Time-Series Forecast** tab to choose a numeric metric and generate predictions!"
                )
            
            predictions = forecast.get("forecast", [])
            pred_desc = ""
            if predictions:
                pred_desc = f"• **Forecast Target**: `{target_metric}`\n"
                pred_desc += f"• **Forecast Period**: {len(predictions)} days ahead\n"
                pred_desc += f"• **Predicted Trend**: {forecast.get('trend_summary', 'stable').upper()}\n\n"
                pred_desc += "**Upcoming Predictions (Estimates)**:\n"
                for p in predictions[:5]:
                    pred_desc += f"  - {p.get('ds')}: {format_number(p.get('yhat'))} (Range: {format_number(p.get('yhat_lower'))} to {format_number(p.get('yhat_upper'))})\n"
                
            return f"Here is the time-series forecasting review:\n\n{pred_desc}"

        # 8. KPIs / Key Metrics
        if any(term in msg for term in ["kpi", "metric", "revenue", "profit", "sales", "total rows"]):
            if not kpis:
                return (
                    f"This dataset has **{col_count}** columns, but no explicit financial or business KPIs (like revenue, profit, or sales) were detected. "
                    "However, we profiled all structural statistics. Ask me about specific columns or insights!"
                )
            
            kpi_list = []
            for k in kpis:
                kpi_list.append(f"• **{k.get('name')}**: {k.get('formatted_value')} (*{k.get('description')}*)")
            
            kpi_str = "\n".join(kpi_list)
            return f"Here are the business and structural KPIs detected in your dataset:\n\n{kpi_str}"

        # 9. Insights / Patterns
        if any(term in msg for term in ["insight", "discover", "pattern", "finding", "correlation", "trend"]):
            if not insights:
                return "I couldn't identify any high-confidence statistical patterns in this dataset structure."
            
            ins_list = []
            for idx, i in enumerate(insights[:5]):
                ins_list.append(f"• **{i.get('category')}**: {i.get('description')} *(Priority: {i.get('priority').upper()} | Confidence: {i.get('confidence_score')}% confidence)*")
            
            ins_str = "\n".join(ins_list)
            return f"Here are the primary insights I extracted from your data:\n\n{ins_str}"

        # 10. Anomalies / Outliers
        if any(term in msg for term in ["anomaly", "outlier", "strange", "error", "outliers"]):
            if not anomalies:
                return (
                    f"My data checks scanned the **{row_count:,}** rows and found no major outliers or statistical anomalies. "
                    "This suggests the records are highly consistent."
                )
            
            anom_desc = f"I detected **{len(anomalies)}** outliers/anomalies in your dataset.\n\n"
            anom_list = []
            for idx, a in enumerate(anomalies[:5]):
                anom_list.append(f"{idx+1}. **Row {a.get('row_index')}** (`{a.get('column_name')}` = {format_number(a.get('value'))}): {a.get('reason')} (Severity: *{a.get('severity')}*)")
            
            return anom_desc + "\n".join(anom_list)

        # 11. Recommendations
        if any(term in msg for term in ["recommend", "recommendation", "action", "do next", "advice"]):
            recs = await self.recommend(insights)
            recs_str = "\n".join([f"{idx+1}. {r}" for idx, r in enumerate(recs)])
            return f"Here are my recommended actions based on the analysis:\n\n{recs_str}"

        # 12. Dynamic Fallback
        col_list = [f"`{c.get('name')}`" for c in columns_profiles]
        col_list_str = ", ".join(col_list[:10])
        if len(col_list) > 10:
            col_list_str += f" and {len(col_list) - 10} more"

        return (
            f"I have profiled the dataset containing **{row_count:,}** rows and **{col_count}** attributes, including: {col_list_str}.\n\n"
            "Try asking me specific questions like:\n"
            f"- *'Tell me about column {columns_profiles[0].get('name') if columns_profiles else 'X'}'*\n"
            "- *'What is the overall health score?'*\n"
            "- *'Are there any missing values?'*\n"
            "- *'Show me recommendations.'*"
        )
